# Generated by Django 5.1.4 on 2026-09-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(default='global', max_length=50),
        ),
    ]
