# Generated by Django 6.1.1 on 2026-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(choices=[('FUT Minna', 'Federal University of Technology, Minna'), ('UNILAG', 'University of Lagos'), ('UI', 'University of Ibadan'), ('ABU', 'Ahmadu Bello University'), ('OAU', 'Obafemi Awolowo University'), ('FUTA', 'Federal University of Technology, Akure'), ('UNIBEN', 'University of Benin'), ('UNIPORT', 'University of Port Harcourt'), ('BUK', 'Bayero University Kano'), ('Other', 'Other University')], default='FUT Minna', max_length=60),
        ),
    ]
