# Generated by Django 6.1.1 on 2026-10-05 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clinic', 'University Clinic & Medical Ambulance 🚑'), ('security', 'Campus Security Post & Gate Patrol 🛡️'), ('sug', 'Student Union (SUG) Welfare Team 🎓'), ('fire', 'Fire & Emergency Safety Service 🚒'), ('counseling', 'Student Mental Health & Counseling Unit 🧠')], max_length=20)),
                ('phone_number', models.CharField(max_length=40)),
                ('campus', models.CharField(default='Both Campuses', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SIWESCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(default='Abuja', max_length=60)),
                ('state', models.CharField(default='FCT', max_length=60)),
                ('industry', models.CharField(help_text='e.g. Software, Telecomm, Civil Engineering, Oil & Gas', max_length=80)),
                ('takes_it_students', models.BooleanField(default=True)),
                ('stipend_info', models.CharField(default='Paid / Unpaid depends on department', max_length=80)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Application tips or accepted faculties')),
            ],
            options={
                'verbose_name_plural': 'SIWES Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('course_code', models.CharField(blank=True, help_text='e.g. CSC 301 or MAT 111', max_length=20)),
                ('department', models.CharField(blank=True, default='All Departments', max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (0, 'All Levels')], default=0)),
                ('urgency', models.CharField(choices=[('normal', 'General Notice'), ('venue_change', 'Venue / Time Shift 📍'), ('urgent', 'Urgent Announcement ⚠️'), ('exam_alert', 'Exam / Test Alert 📝')], default='normal', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LodgeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=150)),
                ('area', models.CharField(choices=[('GK Gate', 'Gidan Kwano Gate Area'), ('Bosso', 'Bosso / Low-Cost'), ('F-Layout', 'F-Layout / Mobil'), ('Barkin Sale', 'Barkin Sale'), ('Tunga', 'Tunga / Minna Town'), ('Other', 'Other Lodge Area')], default='GK Gate', max_length=40)),
                ('rent_estimate', models.CharField(help_text='e.g. ₦120,000 - ₦180,000 / year', max_length=60)),
                ('water_rating', models.PositiveSmallIntegerField(default=4, help_text='1 to 5 stars')),
                ('power_rating', models.PositiveSmallIntegerField(default=3, help_text='1 to 5 stars')),
                ('security_rating', models.PositiveSmallIntegerField(default=4, help_text='1 to 5 stars')),
                ('landlord_rating', models.PositiveSmallIntegerField(default=4, help_text='1 to 5 stars')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodge_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('textbook', 'Textbook / Course Material 📚'), ('drawing_board', 'Engineering Drawing Board / T-Square 📐'), ('lab_coat', 'Lab Coat / Dissection Kit 🥼'), ('calculator', 'Scientific / Graphing Calculator 🧮'), ('gadget', 'Hostel Gadget / Fan / Lamp ⚡'), ('other', 'Other Campus Item 📦')], default='textbook', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False, help_text='Check if giving away for free to a junior student')),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good Condition'), ('fair', 'Fair / Readable')], default='good', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(help_text='WhatsApp number with country code, e.g. 2348012345678', max_length=25)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=200)),
                ('budget_range', models.CharField(help_text='e.g. ₦60k - ₦90k share', max_length=60)),
                ('preferred_area', models.CharField(default='GK Gate', max_length=60)),
                ('cleanliness', models.CharField(default='Very Neat', max_length=40)),
                ('sleep_habit', models.CharField(default='Night Owl (Studies late)', max_length=40)),
                ('study_habit', models.CharField(default='Quiet / Serious', max_length=40)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('whatsapp_number', models.CharField(help_text='e.g. 08012345678', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SIWESLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('department_unit', models.CharField(help_text='e.g. Network Operations Center or Quality Control', max_length=100)),
                ('work_done', models.TextField(help_text='Detailed description of technical tasks completed today')),
                ('skills_acquired', models.CharField(help_text='e.g. Fiber splicing, Django API testing, Soil compaction', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siwes_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-week_number'],
            },
        ),
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('campus', models.CharField(choices=[('Gidan Kwano', 'Main Campus (Gidan Kwano)'), ('Bosso', 'Bosso Campus')], default='Gidan Kwano', max_length=30)),
                ('location_desc', models.CharField(help_text='e.g. Near School of Agriculture or Behind ETF Hall', max_length=200)),
                ('capacity_estimate', models.CharField(blank=True, default='150+ seats', max_length=50)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_sockets', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('gen_on', 'Generator Running ⚡'), ('grid_on', 'NEPA / Public Grid On 💡'), ('no_power', 'Outage / No Light 🌑')], default='gen_on', max_length=20)),
                ('last_reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PowerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gen_on', 'Generator Running ⚡'), ('grid_on', 'NEPA / Public Grid On 💡'), ('no_power', 'Outage / No Light 🌑')], max_length=20)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='campus.studyspot')),
            ],
            options={
                'ordering': ['-voted_at'],
            },
        ),
    ]
