# Generated by Django 6.1.1 on 2026-09-30 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_flashcarddeck_flashcard_studysession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['next_review_date', 'id']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
